### PR TITLE
added modulo functionality for Bigint % int 

### PR DESCRIPTION
**Pull request by SethPoulsen**

### CODE REVIEW

**Comment by kasparsklavins** [comment]
Ignore the failing build.

I'll go over all pull requests this weekend. Thanks!

**Review by kasparsklavins — CHANGES_REQUESTED** [review]
Can you also update readme.md, to include this operator?

**Comment by SethPoulsen** [comment]
Yes, I'll do that.

**Comment by SethPoulsen** [comment]
done.

**Pull request closed without merging**
