### PR TITLE
Fix crash when compare with 0

### PR DESCRIPTION
**Pull request by 1vanK**
https://github.com/kasparsklavins/bigint/issues/5

### CODE REVIEW

**Comment by kasparsklavins** [comment]
Thanks for the pull request, ignore the failing tests.
I would like to see the loop reworked, since essentially it would never end.

**Comment by kasparsklavins** [comment]
Looking at it more closely, the return status is wrong.`
`0` should be returned only when both numbers are equal. Just because one is empty, does not make them equal.
Will you correct it or should I close this?

**Comment by 1vanK** [comment]
```
if (number.size() < a.number.size()) return ...
if (number.size() > a.number.size()) return ...
```
so number.size() == a.number.size()

number.size() == 0 --> a.number.size() == 0 -->  both numbers are equal

anyway I found another lib for my https://mattmccutchen.net/bigint/ (public domain license)

**Comment by 1vanK** [comment]
I understand what you mean

**Pull request closed without merging**
