### PR TITLE
Division operation added.

### PR DESCRIPTION
**Pull request by munsuri**
Request for the inclusion of the division operation taken from SemperPeritus fork.

### CODE REVIEW

**Comment by kasparsklavins** [comment]
Thanks for the pull request. Will look into this by Friday.

**Comment by kasparsklavins** [comment]
`runtime_error()` requires `stdexcept` library, other than that seems ok.

**Comment by munsuri** [comment]
I can take out the stdexcept runtime_error() usage if you don't want to include it

**Comment by kasparsklavins** [comment]
It's fine having it there, just add the necessary library.

**Comment by munsuri** [comment]
There it goes.

**Comment by kasparsklavins** [comment]
Thanks.

**Comment by benlau** [comment]
Seem that the division may not be correct for some cases. For example:

2000109231982371231230 / 12 = 166009102665030935935 (Correct)
2000109231982371231230 / 120 = 16000910266003093593 (Correct)
2000109231982371231230 / 1200 = 1000091026000309359 (Incorrect)

**Comment by kasparsklavins** [comment]
For now reverted the changes in this pull request e093d1ed1d02fb78abf0af3cbd16b4f24750d736

**Pull request merged**
